# Generated by Django 5.0.7 on 2024-07-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Write',
            new_name='Writer',
        ),
    ]
